### ISSUE TITLE
是不是版本有点老了,不兼容最新的hf

### ISSUE THREAD

**Issue by jonny77** [besthird/chat-api#1]
启动警告:  WARNING start_reactor_processes: The onStart event with SWOOLE_BASE is deprecated
访问报错:
Declaration of App\Controller\IndexController::onMessage(Swoole\WebSocket\Server $server, Swoole\Websocket\Frame $frame): void must be compatible with Hyperf\Contract\OnMessageInterface::onMessage

**Comment by limingxinleo** [comment]
启动的警告不用管

**Comment by limingxinleo** [comment]
访问的报错，

你从1.1升级2.0，要跟着文档好好改改

**Comment by jonny77** [comment]
> 访问的报错，
> 
> 你从1.1升级2.0，要跟着文档好好改改
我把代码拷贝到新的框架里面 ,一样的报错

**Comment by limingxinleo** [comment]
。。。

你看下升级文档，你代码有问题啊

**Comment by limingxinleo** [comment]
https://github.com/Gemini-D/chat-api
